/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *action_newProject;
    QAction *action_openProject;
    QAction *action_saveProject;
    QAction *action_saveProjectAs;
    QAction *action_recentProjects;
    QAction *action_exit;
    QAction *action_about;
    QAction *action_show2dmapwnd;
    QAction *action_show3dmapwnd;
    QAction *action_showobjectview;
    QAction *action_showobjectclassview;
    QAction *action_showrelationview;
    QAction *action_showtraitsview;
    QAction *action_show2dmaplayerview;
    QAction *action_importObjectFile;
    QAction *action_exportObjectFile;
    QAction *action_createObject;
    QAction *action_editObject;
    QAction *action_removeObject;
    QAction *action_traits;
    QAction *action_createObjectClass;
    QAction *action_editObjectClass;
    QAction *action_removeObjectClass;
    QAction *action_createRelationClass;
    QAction *action_3;
    QAction *action_4;
    QAction *action_manualCreateRelation;
    QAction *action_batchCreateRelation;
    QAction *action_editRelation;
    QAction *action_removeRelation;
    QAction *action_radarRelationVisual;
    QAction *action_forcelayoutRelationVisual;
    QAction *action_chordRelationVisual;
    QAction *action_2DMapRelationVisual;
    QAction *action_3DMapRelationVisual;
    QAction *action_showConvertWnd;
    QAction *action_importData;
    QAction *action_importObjectClass;
    QAction *action_exportObjectClass;
    QAction *action_removeData;
    QAction *action_filterRule;
    QAction *action_mappingRule;
    QAction *action_mergeRule;
    QAction *action_convert;
    QAction *action_behaviorComponent;
    QAction *action_behaviorDebug;
    QAction *action_behaviorComponentInfo;
    QAction *action_simulatorTime;
    QAction *action_trs;
    QAction *action_srs;
    QAction *action_editRule;
    QAction *action_removeRule;
    QAction *action_showTimeAxisView;
    QWidget *centralWidget;
    QMenuBar *menuBar;
    QMenu *menu_file;
    QMenu *menu_view;
    QMenu *menu_help;
    QMenu *menu_object;
    QMenu *menu;
    QMenu *menu_2;
    QMenu *menu_3;
    QMenu *menu_4;
    QMenu *menu_5;
    QMenu *menu_6;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QToolBar *toolBar_object;
    QToolBar *toolBar_relation;
    QToolBar *toolBar_convert;
    QToolBar *toolBar_bahavior;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1109, 531);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/ModelingTool/Images/modelingtool.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        action_newProject = new QAction(MainWindow);
        action_newProject->setObjectName(QString::fromUtf8("action_newProject"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/ModelingTool/Images/newFile.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_newProject->setIcon(icon1);
        action_openProject = new QAction(MainWindow);
        action_openProject->setObjectName(QString::fromUtf8("action_openProject"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/ModelingTool/Images/openProject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_openProject->setIcon(icon2);
        action_saveProject = new QAction(MainWindow);
        action_saveProject->setObjectName(QString::fromUtf8("action_saveProject"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/ModelingTool/Images/saveProject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_saveProject->setIcon(icon3);
        action_saveProjectAs = new QAction(MainWindow);
        action_saveProjectAs->setObjectName(QString::fromUtf8("action_saveProjectAs"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/ModelingTool/Images/saveProjectAs.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_saveProjectAs->setIcon(icon4);
        action_recentProjects = new QAction(MainWindow);
        action_recentProjects->setObjectName(QString::fromUtf8("action_recentProjects"));
        action_exit = new QAction(MainWindow);
        action_exit->setObjectName(QString::fromUtf8("action_exit"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/ModelingTool/Images/exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_exit->setIcon(icon5);
        action_about = new QAction(MainWindow);
        action_about->setObjectName(QString::fromUtf8("action_about"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/ModelingTool/Images/about.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_about->setIcon(icon6);
        action_show2dmapwnd = new QAction(MainWindow);
        action_show2dmapwnd->setObjectName(QString::fromUtf8("action_show2dmapwnd"));
        action_show2dmapwnd->setCheckable(true);
        action_show2dmapwnd->setChecked(true);
        action_show3dmapwnd = new QAction(MainWindow);
        action_show3dmapwnd->setObjectName(QString::fromUtf8("action_show3dmapwnd"));
        action_show3dmapwnd->setCheckable(true);
        action_show3dmapwnd->setChecked(true);
        action_showobjectview = new QAction(MainWindow);
        action_showobjectview->setObjectName(QString::fromUtf8("action_showobjectview"));
        action_showobjectview->setCheckable(true);
        action_showobjectview->setChecked(true);
        action_showobjectclassview = new QAction(MainWindow);
        action_showobjectclassview->setObjectName(QString::fromUtf8("action_showobjectclassview"));
        action_showobjectclassview->setCheckable(true);
        action_showobjectclassview->setChecked(true);
        action_showrelationview = new QAction(MainWindow);
        action_showrelationview->setObjectName(QString::fromUtf8("action_showrelationview"));
        action_showrelationview->setCheckable(true);
        action_showrelationview->setChecked(true);
        action_showtraitsview = new QAction(MainWindow);
        action_showtraitsview->setObjectName(QString::fromUtf8("action_showtraitsview"));
        action_showtraitsview->setCheckable(true);
        action_showtraitsview->setChecked(true);
        action_show2dmaplayerview = new QAction(MainWindow);
        action_show2dmaplayerview->setObjectName(QString::fromUtf8("action_show2dmaplayerview"));
        action_show2dmaplayerview->setCheckable(true);
        action_show2dmaplayerview->setChecked(false);
        action_importObjectFile = new QAction(MainWindow);
        action_importObjectFile->setObjectName(QString::fromUtf8("action_importObjectFile"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/ModelingTool/Images/importObject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_importObjectFile->setIcon(icon7);
        action_exportObjectFile = new QAction(MainWindow);
        action_exportObjectFile->setObjectName(QString::fromUtf8("action_exportObjectFile"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/ModelingTool/Images/exportObject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_exportObjectFile->setIcon(icon8);
        action_createObject = new QAction(MainWindow);
        action_createObject->setObjectName(QString::fromUtf8("action_createObject"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/ModelingTool/Images/createObject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_createObject->setIcon(icon9);
        action_editObject = new QAction(MainWindow);
        action_editObject->setObjectName(QString::fromUtf8("action_editObject"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/ModelingTool/Images/editObject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_editObject->setIcon(icon10);
        action_removeObject = new QAction(MainWindow);
        action_removeObject->setObjectName(QString::fromUtf8("action_removeObject"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/ModelingTool/Images/removeObject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_removeObject->setIcon(icon11);
        action_traits = new QAction(MainWindow);
        action_traits->setObjectName(QString::fromUtf8("action_traits"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/ModelingTool/Images/traits.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_traits->setIcon(icon12);
        action_createObjectClass = new QAction(MainWindow);
        action_createObjectClass->setObjectName(QString::fromUtf8("action_createObjectClass"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/ModelingTool/Images/createObjectClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_createObjectClass->setIcon(icon13);
        action_editObjectClass = new QAction(MainWindow);
        action_editObjectClass->setObjectName(QString::fromUtf8("action_editObjectClass"));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/ModelingTool/Images/editObjectClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_editObjectClass->setIcon(icon14);
        action_removeObjectClass = new QAction(MainWindow);
        action_removeObjectClass->setObjectName(QString::fromUtf8("action_removeObjectClass"));
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/ModelingTool/Images/removeObjectClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_removeObjectClass->setIcon(icon15);
        action_createRelationClass = new QAction(MainWindow);
        action_createRelationClass->setObjectName(QString::fromUtf8("action_createRelationClass"));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/ModelingTool/Images/createRelationClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_createRelationClass->setIcon(icon16);
        action_3 = new QAction(MainWindow);
        action_3->setObjectName(QString::fromUtf8("action_3"));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/ModelingTool/Images/editRelationClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_3->setIcon(icon17);
        action_4 = new QAction(MainWindow);
        action_4->setObjectName(QString::fromUtf8("action_4"));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/ModelingTool/Images/removeRelationClass.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_4->setIcon(icon18);
        action_manualCreateRelation = new QAction(MainWindow);
        action_manualCreateRelation->setObjectName(QString::fromUtf8("action_manualCreateRelation"));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/ModelingTool/Images/manualCreateRelation.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_manualCreateRelation->setIcon(icon19);
        action_batchCreateRelation = new QAction(MainWindow);
        action_batchCreateRelation->setObjectName(QString::fromUtf8("action_batchCreateRelation"));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/ModelingTool/Images/batchCreateRelation.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_batchCreateRelation->setIcon(icon20);
        action_editRelation = new QAction(MainWindow);
        action_editRelation->setObjectName(QString::fromUtf8("action_editRelation"));
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/ModelingTool/Images/editRelation.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_editRelation->setIcon(icon21);
        action_removeRelation = new QAction(MainWindow);
        action_removeRelation->setObjectName(QString::fromUtf8("action_removeRelation"));
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/ModelingTool/Images/removeRelation.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_removeRelation->setIcon(icon22);
        action_radarRelationVisual = new QAction(MainWindow);
        action_radarRelationVisual->setObjectName(QString::fromUtf8("action_radarRelationVisual"));
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/ModelingTool/Images/radar.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_radarRelationVisual->setIcon(icon23);
        action_forcelayoutRelationVisual = new QAction(MainWindow);
        action_forcelayoutRelationVisual->setObjectName(QString::fromUtf8("action_forcelayoutRelationVisual"));
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/ModelingTool/Images/forceLayout.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_forcelayoutRelationVisual->setIcon(icon24);
        action_chordRelationVisual = new QAction(MainWindow);
        action_chordRelationVisual->setObjectName(QString::fromUtf8("action_chordRelationVisual"));
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/ModelingTool/Images/chordVisual.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_chordRelationVisual->setIcon(icon25);
        action_2DMapRelationVisual = new QAction(MainWindow);
        action_2DMapRelationVisual->setObjectName(QString::fromUtf8("action_2DMapRelationVisual"));
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/ModelingTool/Images/2DMap.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_2DMapRelationVisual->setIcon(icon26);
        action_3DMapRelationVisual = new QAction(MainWindow);
        action_3DMapRelationVisual->setObjectName(QString::fromUtf8("action_3DMapRelationVisual"));
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/ModelingTool/Images/3DMap.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_3DMapRelationVisual->setIcon(icon27);
        action_showConvertWnd = new QAction(MainWindow);
        action_showConvertWnd->setObjectName(QString::fromUtf8("action_showConvertWnd"));
        action_showConvertWnd->setCheckable(true);
        action_showConvertWnd->setChecked(true);
        action_importData = new QAction(MainWindow);
        action_importData->setObjectName(QString::fromUtf8("action_importData"));
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/ModelingTool/Images/importData.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_importData->setIcon(icon28);
        action_importObjectClass = new QAction(MainWindow);
        action_importObjectClass->setObjectName(QString::fromUtf8("action_importObjectClass"));
        action_exportObjectClass = new QAction(MainWindow);
        action_exportObjectClass->setObjectName(QString::fromUtf8("action_exportObjectClass"));
        action_removeData = new QAction(MainWindow);
        action_removeData->setObjectName(QString::fromUtf8("action_removeData"));
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/ModelingTool/Images/removeData.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_removeData->setIcon(icon29);
        action_filterRule = new QAction(MainWindow);
        action_filterRule->setObjectName(QString::fromUtf8("action_filterRule"));
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/ModelingTool/Images/filterRule.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_filterRule->setIcon(icon30);
        action_mappingRule = new QAction(MainWindow);
        action_mappingRule->setObjectName(QString::fromUtf8("action_mappingRule"));
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/ModelingTool/Images/mappingRule.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_mappingRule->setIcon(icon31);
        action_mergeRule = new QAction(MainWindow);
        action_mergeRule->setObjectName(QString::fromUtf8("action_mergeRule"));
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/ModelingTool/Images/mergeRule.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_mergeRule->setIcon(icon32);
        action_convert = new QAction(MainWindow);
        action_convert->setObjectName(QString::fromUtf8("action_convert"));
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/ModelingTool/Images/convert.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_convert->setIcon(icon33);
        action_behaviorComponent = new QAction(MainWindow);
        action_behaviorComponent->setObjectName(QString::fromUtf8("action_behaviorComponent"));
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/ModelingTool/Images/behaviorComponent.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_behaviorComponent->setIcon(icon34);
        action_behaviorDebug = new QAction(MainWindow);
        action_behaviorDebug->setObjectName(QString::fromUtf8("action_behaviorDebug"));
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/ModelingTool/Images/behaviorDebug.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_behaviorDebug->setIcon(icon35);
        action_behaviorComponentInfo = new QAction(MainWindow);
        action_behaviorComponentInfo->setObjectName(QString::fromUtf8("action_behaviorComponentInfo"));
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/ModelingTool/Images/behaviorComponentInfo.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_behaviorComponentInfo->setIcon(icon36);
        action_simulatorTime = new QAction(MainWindow);
        action_simulatorTime->setObjectName(QString::fromUtf8("action_simulatorTime"));
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/ModelingTool/Images/simulatorTime.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_simulatorTime->setIcon(icon37);
        action_trs = new QAction(MainWindow);
        action_trs->setObjectName(QString::fromUtf8("action_trs"));
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/ModelingTool/Images/TRS.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_trs->setIcon(icon38);
        action_srs = new QAction(MainWindow);
        action_srs->setObjectName(QString::fromUtf8("action_srs"));
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/ModelingTool/Images/SRS.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_srs->setIcon(icon39);
        action_editRule = new QAction(MainWindow);
        action_editRule->setObjectName(QString::fromUtf8("action_editRule"));
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/ModelingTool/Images/editRule.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_editRule->setIcon(icon40);
        action_removeRule = new QAction(MainWindow);
        action_removeRule->setObjectName(QString::fromUtf8("action_removeRule"));
        QIcon icon41;
        icon41.addFile(QString::fromUtf8(":/ModelingTool/Images/removeRule.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_removeRule->setIcon(icon41);
        action_showTimeAxisView = new QAction(MainWindow);
        action_showTimeAxisView->setObjectName(QString::fromUtf8("action_showTimeAxisView"));
        action_showTimeAxisView->setCheckable(true);
        action_showTimeAxisView->setChecked(true);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1109, 26));
        menu_file = new QMenu(menuBar);
        menu_file->setObjectName(QString::fromUtf8("menu_file"));
        menu_view = new QMenu(menuBar);
        menu_view->setObjectName(QString::fromUtf8("menu_view"));
        menu_help = new QMenu(menuBar);
        menu_help->setObjectName(QString::fromUtf8("menu_help"));
        menu_object = new QMenu(menuBar);
        menu_object->setObjectName(QString::fromUtf8("menu_object"));
        menu = new QMenu(menuBar);
        menu->setObjectName(QString::fromUtf8("menu"));
        menu_2 = new QMenu(menu);
        menu_2->setObjectName(QString::fromUtf8("menu_2"));
        menu_3 = new QMenu(menu);
        menu_3->setObjectName(QString::fromUtf8("menu_3"));
        menu_4 = new QMenu(menuBar);
        menu_4->setObjectName(QString::fromUtf8("menu_4"));
        menu_5 = new QMenu(menuBar);
        menu_5->setObjectName(QString::fromUtf8("menu_5"));
        menu_6 = new QMenu(menuBar);
        menu_6->setObjectName(QString::fromUtf8("menu_6"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);
        toolBar_object = new QToolBar(MainWindow);
        toolBar_object->setObjectName(QString::fromUtf8("toolBar_object"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_object);
        toolBar_relation = new QToolBar(MainWindow);
        toolBar_relation->setObjectName(QString::fromUtf8("toolBar_relation"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_relation);
        toolBar_convert = new QToolBar(MainWindow);
        toolBar_convert->setObjectName(QString::fromUtf8("toolBar_convert"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_convert);
        toolBar_bahavior = new QToolBar(MainWindow);
        toolBar_bahavior->setObjectName(QString::fromUtf8("toolBar_bahavior"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_bahavior);

        menuBar->addAction(menu_file->menuAction());
        menuBar->addAction(menu_object->menuAction());
        menuBar->addAction(menu->menuAction());
        menuBar->addAction(menu_5->menuAction());
        menuBar->addAction(menu_4->menuAction());
        menuBar->addAction(menu_view->menuAction());
        menuBar->addAction(menu_6->menuAction());
        menuBar->addAction(menu_help->menuAction());
        menu_file->addAction(action_newProject);
        menu_file->addAction(action_openProject);
        menu_file->addAction(action_saveProject);
        menu_file->addAction(action_saveProjectAs);
        menu_file->addAction(action_recentProjects);
        menu_file->addSeparator();
        menu_file->addAction(action_exit);
        menu_view->addAction(action_show2dmapwnd);
        menu_view->addAction(action_show3dmapwnd);
        menu_view->addAction(action_showConvertWnd);
        menu_view->addSeparator();
        menu_view->addAction(action_showobjectview);
        menu_view->addAction(action_showobjectclassview);
        menu_view->addAction(action_showrelationview);
        menu_view->addSeparator();
        menu_view->addAction(action_showtraitsview);
        menu_view->addSeparator();
        menu_view->addAction(action_showTimeAxisView);
        menu_view->addAction(action_show2dmaplayerview);
        menu_help->addAction(action_about);
        menu_object->addAction(action_importObjectFile);
        menu_object->addAction(action_importObjectClass);
        menu_object->addAction(action_exportObjectFile);
        menu_object->addAction(action_exportObjectClass);
        menu_object->addSeparator();
        menu_object->addAction(action_createObjectClass);
        menu_object->addAction(action_editObjectClass);
        menu_object->addAction(action_removeObjectClass);
        menu_object->addSeparator();
        menu_object->addAction(action_createObject);
        menu_object->addAction(action_editObject);
        menu_object->addAction(action_removeObject);
        menu_object->addSeparator();
        menu_object->addAction(action_traits);
        menu->addAction(action_createRelationClass);
        menu->addAction(action_3);
        menu->addAction(action_4);
        menu->addSeparator();
        menu->addAction(menu_2->menuAction());
        menu->addAction(action_editRelation);
        menu->addAction(action_removeRelation);
        menu->addSeparator();
        menu->addAction(menu_3->menuAction());
        menu_2->addAction(action_manualCreateRelation);
        menu_2->addAction(action_batchCreateRelation);
        menu_3->addAction(action_2DMapRelationVisual);
        menu_3->addAction(action_3DMapRelationVisual);
        menu_3->addAction(action_radarRelationVisual);
        menu_3->addAction(action_forcelayoutRelationVisual);
        menu_3->addAction(action_chordRelationVisual);
        menu_4->addAction(action_importData);
        menu_4->addAction(action_removeData);
        menu_4->addSeparator();
        menu_4->addAction(action_filterRule);
        menu_4->addAction(action_mappingRule);
        menu_4->addAction(action_mergeRule);
        menu_4->addAction(action_editRule);
        menu_4->addAction(action_removeRule);
        menu_4->addSeparator();
        menu_4->addAction(action_convert);
        menu_5->addAction(action_behaviorComponent);
        menu_5->addAction(action_behaviorComponentInfo);
        menu_5->addAction(action_behaviorDebug);
        menu_6->addAction(action_trs);
        menu_6->addAction(action_srs);
        menu_6->addSeparator();
        menu_6->addAction(action_simulatorTime);
        mainToolBar->addAction(action_newProject);
        mainToolBar->addAction(action_openProject);
        mainToolBar->addAction(action_saveProject);
        mainToolBar->addAction(action_saveProjectAs);
        toolBar_object->addAction(action_importObjectFile);
        toolBar_object->addAction(action_exportObjectFile);
        toolBar_object->addSeparator();
        toolBar_object->addAction(action_createObjectClass);
        toolBar_object->addAction(action_editObjectClass);
        toolBar_object->addAction(action_removeObjectClass);
        toolBar_object->addSeparator();
        toolBar_object->addAction(action_createObject);
        toolBar_object->addAction(action_editObject);
        toolBar_object->addAction(action_removeObject);
        toolBar_object->addSeparator();
        toolBar_object->addAction(action_traits);
        toolBar_relation->addAction(action_createRelationClass);
        toolBar_relation->addAction(action_3);
        toolBar_relation->addAction(action_4);
        toolBar_relation->addSeparator();
        toolBar_relation->addAction(action_manualCreateRelation);
        toolBar_relation->addAction(action_batchCreateRelation);
        toolBar_relation->addAction(action_editRelation);
        toolBar_relation->addAction(action_removeRelation);
        toolBar_relation->addSeparator();
        toolBar_relation->addAction(action_2DMapRelationVisual);
        toolBar_relation->addAction(action_3DMapRelationVisual);
        toolBar_relation->addAction(action_radarRelationVisual);
        toolBar_relation->addAction(action_forcelayoutRelationVisual);
        toolBar_relation->addAction(action_chordRelationVisual);
        toolBar_convert->addAction(action_importData);
        toolBar_convert->addAction(action_removeData);
        toolBar_convert->addSeparator();
        toolBar_convert->addAction(action_filterRule);
        toolBar_convert->addAction(action_mappingRule);
        toolBar_convert->addAction(action_mergeRule);
        toolBar_convert->addAction(action_editRule);
        toolBar_convert->addAction(action_removeRule);
        toolBar_convert->addSeparator();
        toolBar_convert->addAction(action_convert);
        toolBar_bahavior->addAction(action_behaviorComponent);
        toolBar_bahavior->addAction(action_behaviorComponentInfo);
        toolBar_bahavior->addAction(action_behaviorDebug);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\345\244\232\347\262\222\345\272\246\346\227\266\347\251\272\345\257\271\350\261\241\345\273\272\346\250\241\345\267\245\345\205\267", 0, QApplication::UnicodeUTF8));
        action_newProject->setText(QApplication::translate("MainWindow", "\346\226\260\345\273\272\345\267\245\347\250\213", 0, QApplication::UnicodeUTF8));
        action_newProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0, QApplication::UnicodeUTF8));
        action_openProject->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\345\267\245\347\250\213", 0, QApplication::UnicodeUTF8));
        action_openProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        action_saveProject->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230\345\267\245\347\250\213", 0, QApplication::UnicodeUTF8));
        action_saveProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
        action_saveProjectAs->setText(QApplication::translate("MainWindow", "\345\217\246\345\255\230\345\267\245\347\250\213", 0, QApplication::UnicodeUTF8));
        action_saveProjectAs->setShortcut(QApplication::translate("MainWindow", "F12", 0, QApplication::UnicodeUTF8));
        action_recentProjects->setText(QApplication::translate("MainWindow", "\346\234\200\350\277\221\346\211\223\345\274\200\347\232\204\351\241\271\347\233\256...", 0, QApplication::UnicodeUTF8));
        action_exit->setText(QApplication::translate("MainWindow", "\351\200\200\345\207\272", 0, QApplication::UnicodeUTF8));
        action_about->setText(QApplication::translate("MainWindow", "\345\205\263\344\272\216", 0, QApplication::UnicodeUTF8));
        action_about->setShortcut(QApplication::translate("MainWindow", "Ctrl+A", 0, QApplication::UnicodeUTF8));
        action_show2dmapwnd->setText(QApplication::translate("MainWindow", "\344\272\214\347\273\264\346\230\276\347\244\272\347\252\227\345\217\243", 0, QApplication::UnicodeUTF8));
        action_show3dmapwnd->setText(QApplication::translate("MainWindow", "\344\270\211\347\273\264\346\230\276\347\244\272\347\252\227\345\217\243", 0, QApplication::UnicodeUTF8));
        action_showobjectview->setText(QApplication::translate("MainWindow", "\345\257\271\350\261\241\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        action_showobjectclassview->setText(QApplication::translate("MainWindow", "\347\261\273\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        action_showrelationview->setText(QApplication::translate("MainWindow", "\345\205\263\347\263\273\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        action_showtraitsview->setText(QApplication::translate("MainWindow", "\347\211\271\345\276\201\351\241\271\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        action_show2dmaplayerview->setText(QApplication::translate("MainWindow", "\345\233\276\345\261\202\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        action_importObjectFile->setText(QApplication::translate("MainWindow", "\345\257\274\345\205\245\345\257\271\350\261\241\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        action_exportObjectFile->setText(QApplication::translate("MainWindow", "\345\257\274\345\207\272\345\257\271\350\261\241\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        action_createObject->setText(QApplication::translate("MainWindow", "\345\210\233\345\273\272\345\257\271\350\261\241", 0, QApplication::UnicodeUTF8));
        action_createObject->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+C", 0, QApplication::UnicodeUTF8));
        action_editObject->setText(QApplication::translate("MainWindow", "\347\274\226\350\276\221\345\257\271\350\261\241", 0, QApplication::UnicodeUTF8));
        action_editObject->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+M", 0, QApplication::UnicodeUTF8));
        action_removeObject->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\345\257\271\350\261\241", 0, QApplication::UnicodeUTF8));
        action_removeObject->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+D", 0, QApplication::UnicodeUTF8));
        action_traits->setText(QApplication::translate("MainWindow", "\347\211\271\345\276\201\351\241\271\346\237\245\347\234\213", 0, QApplication::UnicodeUTF8));
        action_createObjectClass->setText(QApplication::translate("MainWindow", "\345\210\233\345\273\272\345\257\271\350\261\241\347\261\273", 0, QApplication::UnicodeUTF8));
        action_createObjectClass->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+C", 0, QApplication::UnicodeUTF8));
        action_editObjectClass->setText(QApplication::translate("MainWindow", "\347\274\226\350\276\221\345\257\271\350\261\241\347\261\273", 0, QApplication::UnicodeUTF8));
        action_editObjectClass->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+M", 0, QApplication::UnicodeUTF8));
        action_removeObjectClass->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\345\257\271\350\261\241\347\261\273", 0, QApplication::UnicodeUTF8));
        action_removeObjectClass->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+D", 0, QApplication::UnicodeUTF8));
        action_createRelationClass->setText(QApplication::translate("MainWindow", "\345\210\233\345\273\272\345\205\263\347\263\273\347\261\273", 0, QApplication::UnicodeUTF8));
        action_3->setText(QApplication::translate("MainWindow", "\347\274\226\350\276\221\345\205\263\347\263\273\347\261\273", 0, QApplication::UnicodeUTF8));
        action_4->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\345\205\263\347\263\273\347\261\273", 0, QApplication::UnicodeUTF8));
        action_manualCreateRelation->setText(QApplication::translate("MainWindow", "\346\211\213\345\212\250\345\210\233\345\273\272", 0, QApplication::UnicodeUTF8));
        action_manualCreateRelation->setShortcut(QApplication::translate("MainWindow", "Ctrl+M", 0, QApplication::UnicodeUTF8));
        action_batchCreateRelation->setText(QApplication::translate("MainWindow", "\346\211\271\351\207\217\345\210\233\345\273\272", 0, QApplication::UnicodeUTF8));
        action_batchCreateRelation->setShortcut(QApplication::translate("MainWindow", "Ctrl+B", 0, QApplication::UnicodeUTF8));
        action_editRelation->setText(QApplication::translate("MainWindow", "\347\274\226\350\276\221\345\205\263\347\263\273", 0, QApplication::UnicodeUTF8));
        action_removeRelation->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\345\205\263\347\263\273", 0, QApplication::UnicodeUTF8));
        action_radarRelationVisual->setText(QApplication::translate("MainWindow", "\351\233\267\350\276\276\345\233\276\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        action_forcelayoutRelationVisual->setText(QApplication::translate("MainWindow", "\345\212\233\345\257\274\345\220\221\345\233\276\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        action_chordRelationVisual->setText(QApplication::translate("MainWindow", "\345\222\214\345\274\246\345\233\276\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        action_2DMapRelationVisual->setText(QApplication::translate("MainWindow", "2D\345\234\260\345\233\276\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        action_3DMapRelationVisual->setText(QApplication::translate("MainWindow", "3D\345\234\260\345\233\276\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        action_showConvertWnd->setText(QApplication::translate("MainWindow", "\346\225\260\346\215\256\346\211\271\351\207\217\350\275\254\346\215\242\347\252\227\345\217\243", 0, QApplication::UnicodeUTF8));
        action_importData->setText(QApplication::translate("MainWindow", "\346\267\273\345\212\240\346\225\260\346\215\256\346\272\220", 0, QApplication::UnicodeUTF8));
        action_importObjectClass->setText(QApplication::translate("MainWindow", "\345\257\274\345\205\245\345\257\271\350\261\241\347\261\273\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        action_exportObjectClass->setText(QApplication::translate("MainWindow", "\345\257\274\345\207\272\345\257\271\350\261\241\347\261\273\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        action_removeData->setText(QApplication::translate("MainWindow", "\347\247\273\351\231\244\346\225\260\346\215\256\346\272\220", 0, QApplication::UnicodeUTF8));
        action_filterRule->setText(QApplication::translate("MainWindow", "\350\277\207\346\273\244\350\247\204\345\210\231", 0, QApplication::UnicodeUTF8));
        action_mappingRule->setText(QApplication::translate("MainWindow", "\346\230\240\345\260\204\350\247\204\345\210\231", 0, QApplication::UnicodeUTF8));
        action_mergeRule->setText(QApplication::translate("MainWindow", "\350\236\215\345\220\210\350\247\204\345\210\231", 0, QApplication::UnicodeUTF8));
        action_convert->setText(QApplication::translate("MainWindow", "\346\211\247\350\241\214\350\275\254\346\215\242", 0, QApplication::UnicodeUTF8));
        action_behaviorComponent->setText(QApplication::translate("MainWindow", "\347\224\237\346\210\220\350\241\214\344\270\272\347\273\204\344\273\266\346\241\206\346\236\266", 0, QApplication::UnicodeUTF8));
        action_behaviorDebug->setText(QApplication::translate("MainWindow", "\350\241\214\344\270\272\350\260\203\350\257\225", 0, QApplication::UnicodeUTF8));
        action_behaviorComponentInfo->setText(QApplication::translate("MainWindow", "\346\237\245\347\234\213\350\241\214\344\270\272\347\273\204\344\273\266\344\277\241\346\201\257", 0, QApplication::UnicodeUTF8));
        action_simulatorTime->setText(QApplication::translate("MainWindow", "\344\273\277\347\234\237\346\227\266\351\227\264\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        action_trs->setText(QApplication::translate("MainWindow", "\346\227\266\351\227\264\345\217\202\350\200\203", 0, QApplication::UnicodeUTF8));
        action_srs->setText(QApplication::translate("MainWindow", "\347\251\272\351\227\264\345\217\202\350\200\203", 0, QApplication::UnicodeUTF8));
        action_editRule->setText(QApplication::translate("MainWindow", "\347\274\226\350\276\221\350\247\204\345\210\231", 0, QApplication::UnicodeUTF8));
        action_removeRule->setText(QApplication::translate("MainWindow", "\347\247\273\351\231\244\350\247\204\345\210\231", 0, QApplication::UnicodeUTF8));
        action_showTimeAxisView->setText(QApplication::translate("MainWindow", "\346\227\266\351\227\264\350\275\264\350\247\206\345\233\276", 0, QApplication::UnicodeUTF8));
        menu_file->setTitle(QApplication::translate("MainWindow", "\346\226\207\344\273\266(&File)", 0, QApplication::UnicodeUTF8));
        menu_view->setTitle(QApplication::translate("MainWindow", "\350\247\206\345\233\276(&View)", 0, QApplication::UnicodeUTF8));
        menu_help->setTitle(QApplication::translate("MainWindow", "\345\270\256\345\212\251(&Help)", 0, QApplication::UnicodeUTF8));
        menu_object->setTitle(QApplication::translate("MainWindow", "\345\257\271\350\261\241(&Object)", 0, QApplication::UnicodeUTF8));
        menu->setTitle(QApplication::translate("MainWindow", "\345\205\263\347\263\273(&Relation)", 0, QApplication::UnicodeUTF8));
        menu_2->setTitle(QApplication::translate("MainWindow", "\345\210\233\345\273\272\345\205\263\347\263\273", 0, QApplication::UnicodeUTF8));
        menu_3->setTitle(QApplication::translate("MainWindow", "\345\205\263\347\263\273\345\217\257\350\247\206\345\214\226", 0, QApplication::UnicodeUTF8));
        menu_4->setTitle(QApplication::translate("MainWindow", "\350\275\254\346\215\242(&Convert)", 0, QApplication::UnicodeUTF8));
        menu_5->setTitle(QApplication::translate("MainWindow", "\350\241\214\344\270\272(Behavior)", 0, QApplication::UnicodeUTF8));
        menu_6->setTitle(QApplication::translate("MainWindow", "\350\256\276\347\275\256(&Settings)", 0, QApplication::UnicodeUTF8));
        toolBar_object->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0, QApplication::UnicodeUTF8));
        toolBar_relation->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0, QApplication::UnicodeUTF8));
        toolBar_convert->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0, QApplication::UnicodeUTF8));
        toolBar_bahavior->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
